/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ANNIndexManager */

#ifndef _Included_ANNIndexManager
#define _Included_ANNIndexManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ANNIndexManager
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ANNIndexManager_init
  (JNIEnv *, jclass);

/*
 * Class:     ANNIndexManager
 * Method:    new_bf_index
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ANNIndexManager_new_1bf_1index
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ANNIndexManager
 * Method:    add
 * Signature: (Ljava/lang/String;[FI)V
 */
JNIEXPORT void JNICALL Java_ANNIndexManager_add
  (JNIEnv *, jclass, jstring, jfloatArray, jint);

/*
 * Class:     ANNIndexManager
 * Method:    build
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ANNIndexManager_build
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ANNIndexManager
 * Method:    search
 * Signature: (Ljava/lang/String;I[F)[I
 */
JNIEXPORT jintArray JNICALL Java_ANNIndexManager_search
  (JNIEnv *, jclass, jstring, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
