/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hora_app_ANNIndex */

#ifndef _Included_com_hora_app_ANNIndex
#define _Included_com_hora_app_ANNIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hora_app_ANNIndex
 * Method:    new_bf_index
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_hora_app_ANNIndex_new_1bf_1index
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_hora_app_ANNIndex
 * Method:    add
 * Signature: (Ljava/lang/String;[FI)V
 */
JNIEXPORT void JNICALL Java_com_hora_app_ANNIndex_add
  (JNIEnv *, jclass, jstring, jfloatArray, jint);

/*
 * Class:     com_hora_app_ANNIndex
 * Method:    build
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hora_app_ANNIndex_build
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_hora_app_ANNIndex
 * Method:    search
 * Signature: (Ljava/lang/String;I[F)[I
 */
JNIEXPORT jintArray JNICALL Java_com_hora_app_ANNIndex_search
  (JNIEnv *, jclass, jstring, jint, jfloatArray);

/*
 * Class:     com_hora_app_ANNIndex
 * Method:    load
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hora_app_ANNIndex_load
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_hora_app_ANNIndex
 * Method:    dump
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hora_app_ANNIndex_dump
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
